### ISSUE TITLE
[bug] doesn't work on macOS with Google Chrome

### ISSUE THREAD

**Issue by SimJoSt** [burkybang/Google-Meet-Auto-Disable-Camera#1]
We are using Google Meet via GSuite/work Google accounts. After installing this extension and opening a Meet url, the video/camera is still activated by default.

**Comment by burkybang** [comment]
Hi @SimJoSt. I also use Google Meet via a GSuite/work Google account on macOS. I just tested it again, and it's working for me. 🤔
I do have a theory as to why it's not working for you. I just submitted version 1.0.3 to Google for review. Once that version is approved and updated on your Mac, please let me know if it starts working.

**Comment by burkybang** [comment]
@SimJoSt Could you please confirm if it's working for you now?

**Comment by burkybang** [comment]
No response from @SimJoSt in 2 weeks, so I'm closing this issue.

**Comment by SimJoSt** [comment]
Sorry, I haven't checked it yet, as I circumvented the issue by closing the MacBook and using an external display.
I'll try again as soon as I can.
