### ISSUE TITLE
Can you also add auto mute?

### ISSUE THREAD

**Issue by anshulahuja98** [burkybang/Google-Meet-Auto-Disable-Camera#2]
Add  option to also auto-mute on join.

**Comment by burkybang** [comment]
Thanks for the feature request! I've added support for this in v1.1.0.

**Comment by burkybang** [comment]
I just finished submitting v1.1.0 to Google. They've been pretty quick to approve lately. It could be out in a day or two.

**Comment by burkybang** [comment]
v1.1.0 is out now.
