### ISSUE TITLE
check for "Ctrl + D"

### ISSUE THREAD

**Issue by jjimenezshaw** [burkybang/Google-Meet-Auto-Disable-Camera#3]
In my chromium browser, the `aria-label` for the buttons is using a capital letter, `D` and `E`.
To fix that you probably have to change the querySelector query with the ignorecase option
`[aria-label$=" + ${buttonKey})" i]`

**Comment by burkybang** [comment]
Thanks! That will be released in v1.1.0.

**Comment by burkybang** [comment]
I just finished submitting v1.1.0 to Google. They've been pretty quick to approve lately. It could be out in a day or two.

**Comment by burkybang** [comment]
v1.1.0 is out now.

**Comment by burkybang** [comment]
v1.1.0 is out. Let me know if it's working for you now.

**Comment by jjimenezshaw** [comment]
It does work... but only if I have the `Developer Tools` open. I think it is another problem.

**Comment by burkybang** [comment]
That's strange. It's working for me without dev tools open.
